@startuml

' Title
title Conceptual Domain Model

skinparam classAttributeIconSize 0
hide empty members
hide attributes

skinparam class {
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

entity Appointment {
    - id
    - requestID
    - roomID
    - dateAndTime
    - status
}

entity Equipment{
    - name
    - description
}

entity SurgeryRoom{
    - roomNumber
    - type
    - capacity
    '- assignedEquipment
    - currentStatus
    - maintenanceSlots
}

entity User{
    - username
    - role
    - email
}
note top of User : This logic is abstracted by the backend and is implemented in the IAM process

entity OperationType{
    - id
    - name
    '- requiredStaffBySpecialization
    - estimatedDuration
    - isActive
}

entity OperationRequest{
    - id
    - patientID
    - doctorID
    - operationTypeID
    - deadlineDate
    - priority
}

entity Staff{
    - firstName
    - lastName
    - fullName
    - licenseNumber
    '- specialization
    - contactInformation
    - availabilitySlots
    - isActive
}

entity Patient{
    - firstName
    - lastName
    - fullName
    - dateOfBirth
    - gender
    - medicalRecordNumber
    - contactInformation
    - allergiesAndConditions
    - emergencyContact
    '- appointmentHistory
}

entity Specialization{
    - name
    - description
}

entity PendingRequest{
    - id
    - userID
    - attributeName
    - pendingValue
    - oldValue
}
note top of PendingRequest
Used to persist a change which needs 
a user confirmation to take effect.
end note

entity Log{
    - timestamp
    - action
    - author
}
note top of Log
They will be used to keep track of the actions
taken by the users in compliance with GDPR.
end note




' Relationships
User "1" -- "0..*" Patient : has >
User "1" -- "0..*" Staff : has >
User "1" -- "1..*" OperationType : adds >

Patient "1" -- "*" Appointment : has >
Patient "1" -- "*" OperationRequest : has >

Staff "*" -- "1" Specialization : has >
Staff "*" -- "*" OperationRequest : submits and edits >
Staff "*" -- "*" Appointment : handles >

OperationType "*" -- "*" Specialization : requires >
OperationType "1" -- "*" OperationRequest : specifies >

Appointment "1" -- "1" SurgeryRoom : in >
Appointment "1" -- "1" OperationRequest :  generates <

SurgeryRoom "1" -- "*" Equipment : contains >

@enduml