@startuml


title US 5.1.20 - As an Admin, I want to add new types of operations

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

actor "Admin" as Admin

participant "Route" as Route
participant ":OperationTypeController" as Controller
participant ":AuthService" as AS
participant ":OperationTypeService" as Service
participant "OperationType" as OperationType
participant ":OperationTypeRepository" as Repository
participant ":LogServce" as LogService


activate Admin

Admin -> Route: POST /api/OperationType/Create

activate Route

Route -> Controller: CreateOperationType(...)

activate Controller

Controller -> AS: getAuthenticatedUserEmail(accessToken)

activate AS

AS --> Controller: adminEmail

deactivate AS

Controller -> Service: createOperationTypeAsync(operationType, adminEmail)

activate Service

Service -> Repository: OperationTypeExists(OperationTypeName)

activate Repository

Repository --> Service: false

deactivate Repository

Service -> OperationType**: new OperationType(...)

activate OperationType

OperationType --> Service: operationType

deactivate OperationType

Service -> Repository: AddAsync(operationType)

activate Repository

Repository --> Service: 

deactivate Repository

Service -> LogService: CreateLogAsync(message, adminEmail)

activate LogService

LogService --> Service:

deactivate LogService

Service --> Controller: Ok

deactivate Service

Controller --> Route: Ok

deactivate Controller

Route --> Admin: Operatio Type created successfully

@enduml