@startuml
title Sequence Diagram 
skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

actor Patient
participant "Route" as UI
participant "PatientController" as Controller
participant "PatientService" as userS
participant "PatientRepository" as userR
participant "PendingRequestService" as penS
participant "PendingRequestRepository" as penR

participant "LogService" as LogS
participant "LogRepository" as LogR
participant "PendingRequest" as pen
participant "Patient" as user
database "DataBase" as db

activate Patient
Patient -> UI: HttpGet("acceptPendingRequests")
activate UI
UI -> Controller:AcceptPatientPendingRequests([FromQuery] string requestIds)
activate Controller
Controller -> userS : AcceptRequests(requests)
activate userS

loop for each pending request

userS -> penS: GetByIdAsync(requestID)
activate penS
penS -> penR : GetByIdAsync(requestID)
activate penR
penR -> db : getById(requestID)
activate db
db --> penR: pendingRequest
deactivate db
penR --> penS : pendingRequest
deactivate penR
penS --> userS : pendingRequest
deactivate penS

userS -> pen : getPatientID()
activate pen 
pen --> userS : Value
deactivate pen

userS -> userR : GetByIdAsync(id)
activate userR 
userR -> db : getById(id)
activate db
db --> userR: patient
deactivate db
userR --> userS: patient
deactivate userR

userS -> pen : getValue()
activate pen 
pen --> userS : Value
deactivate pen

userS -> user: changeXAttribute(value)
activate user 
user --> userS 
deactivate user

userS -> LogS : CreateLogAsync(log, email)
activate LogS
LogS -> LogR : CreateLogAsync(log, email)
activate LogR
LogR -> db : add(log)
activate db 
db --> LogR 
deactivate db
LogR --> LogS
deactivate LogR
LogS --> userS
deactivate LogS
end 
userS --> Controller : true
deactivate userS
Controller --> UI
deactivate Controller 
UI --> Patient 
deactivate Ui
deactivate Patient




















@enduml