### Use Case Diagram for US 5.1.3

@startuml

actor Patient
actor "External IAM System" as IAM

usecase "Register" as UC_Register
usecase "Provide Personal Details" as UC_ProvideDetails
usecase "Validate Email" as UC_ValidateEmail

Patient -> UC_Register
UC_Register --> UC_ProvideDetails
IAM --> UC_ValidateEmail
UC_Register --> IAM : "Use IAM for Registration"
UC_ValidateEmail --> Patient : "Send Verification Email"

@enduml