@startuml


title US 5.1.6 - As a (non-authenticated) Backoffice User, I want to log in to the system using my credentials

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

actor "Backoffice User" as BU

participant "Route" as Route
participant ":UserController" as PRC
participant ":AuthService" as AS
participant "External IAM Provider" as IAM

activate BU

BU -> Route: POST /api/User/login-user

activate Route

Route -> PRC: LogInUserAsync(email, password)

activate PRC

PRC -> AS: SignInAsync(email, password)

activate AS

AS -> IAM: InitiateAuthAsync(request)

activate IAM

IAM --> AS: InitiateAuthAsyncResponse

deactivate IAM

AS --> PRC: AccessToken

deactivate AS

PRC --> Route: AccessToken

deactivate PRC

Route --> BU: AccessToken

deactivate Route

deactivate BU



@enduml