// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Models;
using AppContext = src.Models.AppContext;

#nullable disable

namespace sem_5_24_25_043.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20241022122924_ResetDB")]
    partial class ResetDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.OperationRequestAggregate.OperationRequest", b =>
                {
                    b.Property<string>("operationRequestID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deadlineDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operationTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientID")
                        .HasColumnType("int");

                    b.Property<string>("priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("operationRequestID");

                    b.ToTable("OperationRequests", (string)null);

                    b.HasData(
                        new
                        {
                            operationRequestID = "1",
                            Id = "1",
                            deadlineDate = "01/01/2025 00:00:00",
                            doctorID = "s202400001",
                            operationTypeID = "Knee Surgery",
                            patientID = 1,
                            priority = "Emergency"
                        },
                        new
                        {
                            operationRequestID = "2",
                            Id = "2",
                            deadlineDate = "01/01/2025 00:00:00",
                            doctorID = "s202400002",
                            operationTypeID = "Heart Surgery",
                            patientID = 2,
                            priority = "Effective"
                        });
                });

            modelBuilder.Entity("Domain.PatientAggregate.Patient", b =>
                {
                    b.Property<string>("medicalRecordNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allergiesAndConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("appointmentHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("emergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("medicalRecordNumber");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("medicalRecordNumber")
                        .IsUnique();

                    b.HasIndex("phoneNumber")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            medicalRecordNumber = "1",
                            Id = "1",
                            allergiesAndConditions = "[]",
                            appointmentHistory = "{}",
                            dateOfBirth = "1/1/1999",
                            email = "john@email.com",
                            emergencyContact = "{\"name\":\"Jane\",\"phoneNumber\":\"919919919\"}",
                            firstName = "John",
                            fullName = "John Doe",
                            gender = "Male",
                            lastName = "Doe",
                            phoneNumber = "919919919"
                        },
                        new
                        {
                            medicalRecordNumber = "2",
                            Id = "2",
                            allergiesAndConditions = "[]",
                            appointmentHistory = "{}",
                            dateOfBirth = "1/1/1999",
                            email = "Jane@email.com",
                            emergencyContact = "{\"name\":\"Jane\",\"phoneNumber\":\"919999119\"}",
                            firstName = "Jane",
                            fullName = "Jane Does",
                            gender = "Male",
                            lastName = "Does",
                            phoneNumber = "919991919"
                        });
                });

            modelBuilder.Entity("Log", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("OperationType", b =>
                {
                    b.Property<string>("operationTypeName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estimatedDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("specializations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("operationTypeName");

                    b.ToTable("OperationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            operationTypeName = "Heart Surgery",
                            Id = "Heart Surgery",
                            estimatedDuration = "3:15",
                            isActive = true,
                            specializations = "{\"Cardiology\":1}"
                        },
                        new
                        {
                            operationTypeName = "Knee Surgery",
                            Id = "Knee Surgery",
                            estimatedDuration = "2:0",
                            isActive = true,
                            specializations = "{\"Orthopedics\":2}"
                        });
                });

            modelBuilder.Entity("PendingRequest", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("attributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pendingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requestID")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("requestID")
                        .IsUnique();

                    b.ToTable("PendingRequests", (string)null);
                });

            modelBuilder.Entity("Staff", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("availabilitySlots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("licenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("specializationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("licenseNumber")
                        .IsUnique();

                    b.HasIndex("phoneNumber")
                        .IsUnique();

                    b.ToTable("Staffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "D202400001",
                            availabilitySlots = "",
                            email = "D202400001@medopt.com",
                            firstName = "John",
                            fullName = "John,Doe",
                            isActive = true,
                            lastName = "Doe",
                            licenseNumber = "123456",
                            phoneNumber = "919919919",
                            specializationID = "Cardiology",
                            staffID = "D202400001"
                        },
                        new
                        {
                            Id = "D202400011",
                            availabilitySlots = "",
                            email = "D202400011@medopt.com",
                            firstName = "Carlos",
                            fullName = "Carlos,Moedas",
                            isActive = true,
                            lastName = "Moedas",
                            licenseNumber = "121236",
                            phoneNumber = "919911319",
                            specializationID = "Orthopedics",
                            staffID = "D202400011"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
