// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Models;
using AppContext = src.Models.AppContext;

#nullable disable

namespace sem_5_24_25_043.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.OperationRequestAggregate.OperationRequest", b =>
                {
                    b.Property<string>("operationRequestID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deadlineDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operationTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("operationRequestID");

                    b.ToTable("OperationRequests", (string)null);

                    b.HasData(
                        new
                        {
                            operationRequestID = "1",
                            Id = "1",
                            deadlineDate = "01/01/2025 00:00:00",
                            doctorID = "D202400001",
                            operationTypeID = "Knee Surgery",
                            patientID = "1",
                            priority = "Emergency"
                        },
                        new
                        {
                            operationRequestID = "2",
                            Id = "2",
                            deadlineDate = "01/01/2025 00:00:00",
                            doctorID = "D202400001",
                            operationTypeID = "Heart Surgery",
                            patientID = "2",
                            priority = "Effective"
                        },
                        new
                        {
                            operationRequestID = "3",
                            Id = "3",
                            deadlineDate = "01/01/2025 00:00:00",
                            doctorID = "s202400002",
                            operationTypeID = "Heart Surgery",
                            patientID = "2",
                            priority = "Effective"
                        });
                });

            modelBuilder.Entity("Domain.PatientAggregate.Patient", b =>
                {
                    b.Property<string>("MedicalRecordNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AllergiesAndConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MedicalRecordNumber");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            MedicalRecordNumber = "1",
                            AllergiesAndConditions = "[]",
                            AppointmentHistory = "{}",
                            DateOfBirth = "1/1/1999",
                            Email = "john@email.com",
                            EmergencyContact = "{\"Name\":\"Jane\",\"PhoneNumber\":\"\\u002B351919919919\"}",
                            FirstName = "John",
                            FullName = "John Doe",
                            Gender = "Male",
                            Id = "1",
                            LastName = "Doe",
                            PhoneNumber = "+351919919919"
                        },
                        new
                        {
                            MedicalRecordNumber = "2",
                            AllergiesAndConditions = "[]",
                            AppointmentHistory = "{}",
                            DateOfBirth = "1/1/1999",
                            Email = "Jane@email.com",
                            EmergencyContact = "{\"Name\":\"Jane\",\"PhoneNumber\":\"\\u002B351919999119\"}",
                            FirstName = "Jane",
                            FullName = "Jane Does",
                            Gender = "Male",
                            Id = "2",
                            LastName = "Does",
                            PhoneNumber = "+351919991919"
                        });
                });

            modelBuilder.Entity("Log", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("OperationType", b =>
                {
                    b.Property<string>("operationTypeName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estimatedDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("specializations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("operationTypeName");

                    b.ToTable("OperationTypes", (string)null);
                });

            modelBuilder.Entity("PendingRequest", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("attributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pendingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requestID")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("requestID")
                        .IsUnique();

                    b.ToTable("PendingRequests", (string)null);
                });

            modelBuilder.Entity("Staff", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("availabilitySlots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("licenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("specializationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("licenseNumber")
                        .IsUnique();

                    b.HasIndex("phoneNumber")
                        .IsUnique();

                    b.ToTable("Staffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "D202400001",
                            availabilitySlots = "",
                            email = "d123@doctor.com",
                            firstName = "John",
                            fullName = "John,Doe",
                            isActive = true,
                            lastName = "Doe",
                            licenseNumber = "123456",
                            phoneNumber = "+351919919919",
                            specializationID = "Cardiology",
                            staffID = "D202400001"
                        },
                        new
                        {
                            Id = "D202400011",
                            availabilitySlots = "",
                            email = "D202400011@medopt.com",
                            firstName = "Carlos",
                            fullName = "Carlos,Moedas",
                            isActive = true,
                            lastName = "Moedas",
                            licenseNumber = "121236",
                            phoneNumber = "+351919911319",
                            specializationID = "Orthopedics",
                            staffID = "D202400011"
                        });
                });

            modelBuilder.Entity("src.Domain.AppointmentAggregate.Appointment", b =>
                {
                    b.Property<string>("appointmentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateAndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("requestID")
                        .HasColumnType("int");

                    b.Property<int>("roomID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("appointmentID");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            appointmentID = "1",
                            Id = "1",
                            dateAndTime = "2024-10-24 18:16:38",
                            requestID = 1,
                            roomID = 1,
                            status = "Scheduled"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
