@startuml


title US 5.1.3 - As a Patient, I want to self-register so that I can use the application

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

actor "Patient" as P

participant "External IAM Provider" as IAM
participant "API" as API
participant ":PatientController" as PC
participant ":PatientService" as PS
participant ":PatientRepository" as PR
participant ":EmailService" as ES

activate P

P -> IAM: Tries to self-register

activate IAM

IAM -> P: Asks for login details

deactivate IAM

P -> IAM: Provides login details

activate IAM

IAM -> API: validate patient email

activate API

API -> PC: validateEmail(email)

activate PC

PC -> PS: validateEmail(email)

activate PS

PS -> PR: findPatientByEmail(email)

activate PR

PR --> PS: result

alt "Patient not found"

    PS --> PC: false

    PC --> API: false

    API --> IAM: false

    IAM --> P: shows "Patient not found"

else "Patient found"

    PS -> ES: sendPatientRegistrationEmail(email)

    activate ES

    ES --> PS: 

    deactivate ES

    PS --> PC: true

    PC --> API: true

    API --> IAM: true

    IAM --> P: shows "User Registrered, check your email"
end















@enduml