@startuml
title Sequence Diagram
skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

actor Doctor
participant "Route" as UI
participant "OperationRequestController" as Controller
participant "OperationRequestService" as OperationRequestServ
participant "OperationRequestRepository" as OperationRequestRepo
participant "LogService" as LogServ
participant "LogRepository" as LogRepo
participant "OperationRequest" as OperationRequest
participant "OperationRequestDto" as OperationRequestDto
database "Data Base" as db 



activate Doctor

Doctor-> UI: HttpPatch("{id}")  
activate UI
UI -> Controller :UpdateOperationRequest(id,operationRequestDto)
activate Controller 
Controller-> OperationRequestServ : UpdateOperationRequestAsync(id, operationRequestDto, doctorEmail)

activate OperationRequestServ
OperationRequestServ -> OperationRequestRepo : GetByIdAsync(new OperationRequest
activate OperationRequestRepo
OperationRequestRepo -> db : get(id)
activate db
db --> OperationRequestRepo: OperationRequest

deactivate db
OperationRequestRepo --> OperationRequestServ : OperationRequest

deactivate OperationRequestRepo
loop OperationRequest attribute
OperationRequestServ-> OperationRequestDto : getXattribute
activate OperationRequestDto

OperationRequestDto--> OperationRequestServ: Xattribute
deactivate OperationRequestDto

OperationRequestServ--> OperationRequest: changeXattribute
activate  OperationRequest
OperationRequest --> OperationRequestServ 
deactivate OperationRequest

OperationRequestServ -> LogServ : CreateLogAsync(log, email)
activate LogServ
LogServ -> LogRepo : AddAsync(log)
activate LogRepo 
LogRepo -> db: Add(Log)
activate db
db --> LogRepo 
deactivate db
LogRepo --> LogServ
deactivate LogRepo
LogServ --> OperationRequestServ: true
deactivate LogServ
end

OperationRequestServ -> OperationRequestRepo: updateAsync(operationRequest)
activate OperationRequestRepo
OperationRequestRepo -> db : update(operationRequest) 
activate db 
db --> OperationRequestRepo
deactivate db
OperationRequestRepo --> OperationRequestServ
deactivate OperationRequestRepo
OperationRequestServ --> Controller : true 

deactivate OperationRequestServ

Controller --> UI : true
deactivate Controller 
UI --> Doctor : true 
deactivate UI



deactivate Doctor

















@enduml