@startuml


title US 5.1.8 - As an Admin, I want to create a new patient profile, so that I can register their personal details and medical history.

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor LemonChiffon
    ArrowColor Brown
    BorderColor SaddleBrown
}

actor "Admin" as A

participant "Route" as Route
participant "PatientController" as PC
participant "PatientService" as PS
participant "Patient" as P
participant "PatientRepository" as PR



activate A

A -> Route: POST /api/Patient/Create

activate Route

Route -> PC: CreatePatient(...)

activate PC

PC -> PS: CreatePatientAsync(...)

activate PS

PS -> PS: ValidatePatientInformation(email, phone number)

activate PS

PS -> PR: PatientExists(email, phone number)

activate PR

PR --> PS: false

deactivate PR

deactivate PS



PS -> P**: new Patient(...)

activate P

P --> PS: patient

deactivate P

PS -> PR: AddAsync(patient)

activate PR

PR --> PS: 

deactivate PR

PS --> PC: patientDTO

deactivate PS

PC --> Route: patientDTO

deactivate PC

Route --> A: Patient Data

deactivate Route

deactivate A






@enduml