name: Backend CI/CD

on:
  push:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install Dependencies
        run: dotnet restore sem_5_24_25_043.sln

      - name: Run Integration Tests
        run: dotnet test sem_5_24_25_043.sln --filter "FullyQualifiedName~IntegrationTests" --no-restore --verbosity normal

      - name: Run Unit Tests
        run: dotnet test sem_5_24_25_043.sln --filter "FullyQualifiedName~UnitTests" --no-restore --verbosity normal
