name: Backend CI/CD

on:
  push:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Verify Directory Structure
        run: ls -R

      - name: Adjust File Paths for CI Environment
        run: |
          sed -i 's|tests/IntegrationTests/IntegrationTests.csproj|../tests/IntegrationTests/IntegrationTests.csproj|' sem_5_24_25_043.sln
          sed -i 's|tests/UnitTests/tests.csproj|../tests/UnitTests/tests.csproj|' sem_5_24_25_043.sln

      - name: Install Dependencies
        run: dotnet restore ./sem_5_24_25_043.sln

      - name: Run Integration Tests
        run: dotnet test ./tests/IntegrationTests --no-restore --verbosity normal

      - name: Run Unit Tests
        run: dotnet test ./tests/UnitTests --no-restore --verbosity normal
