name: Deploy Backend

on:
  workflow_run:
    workflows:
      - Backend CI/CD
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            
            echo "Navigating to the project folder..."
            cd /var/www/backend/sem_5_24_25_043

            echo "Stopping the running application..."
            sudo systemctl stop backend.service || true

            echo "Pulling the latest code..."
            git pull origin production

            echo "Cleaning previous build artifacts..."
            dotnet clean src

            echo "Building the application..."
            dotnet build src -p:NoWarn=*

            echo "Restarting the application service..."
            sudo systemctl restart backend.service

            echo "Deployment completed successfully!"
