name: Deploy Backend

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /var/www/backend/sem_5_24_25_043

            echo "Pulling latest code..."
            git pull origin production

            echo "Change directory to the project folder..."
            cd src

            echo "Building the application..."
            dotnet build --no-warn

            echo "Restarting the service..."
            sudo systemctl restart backend.service

            echo "Deployment completed!"
